<a href="https://colab.research.google.com/github/riteshdurgiani/DLPracs/blob/main/DL_Pracs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# McCulloch Pitts


In [ ]:
import numpy as np


In [ ]:
def makeMatrix(arr,n):
  l = []
  for i in range(0,n):
    l.append(arr[i])
  matrix.append(l)

def generateAllBinaryStrings(n,arr,i):
  if i == n:
    makeMatrix(arr,n)
    return 
  arr[i] = 0
  generateAllBinaryStrings(n,arr,i+1)

  arr[i] = 1
  generateAllBinaryStrings(n,arr,i+1)



In [ ]:
#AND GATE 
col = int(input("Enter the number of inputs"))
row = pow(2,col) 

arr = [None] * col
matrix = [[]]
generateAllBinaryStrings(col,arr,0)

print()

W = np.ones((col,) , dtype='int')

for i in range(1,row+1):
  sum = 0
  for j in range(col):
    sum += matrix[i][j] * W[j]
  if sum >= col:
    for r in range(col):
      print(matrix[i][r],end =' ')
    print(1)
  else:
    for r in range(col):
      print(matrix[i][r],end=' ')
    print(0)

Enter the number of inputs3

0 0 0 0
0 0 1 0
0 1 0 0
0 1 1 0
1 0 0 0
1 0 1 0
1 1 0 0
1 1 1 1


In [ ]:
#NAND GATE  
col = int(input("Enter the number of inputs"))
row = pow(2,col) 

arr = [None] * col
matrix = [[]]
generateAllBinaryStrings(col,arr,0)

print()

W = -1*(np.ones((col,) , dtype='int'))

for i in range(1,row+1):
  sum = 0
  for j in range(col):
    sum += matrix[i][j] * W[j]
  if sum >= -(col-1):
    for r in range(col):
      print(matrix[i][r],end =' ')
    print(1)
  else:
    for r in range(col):
      print(matrix[i][r],end=' ')
    print(0)

Enter the number of inputs3

0 0 0 1
0 0 1 1
0 1 0 1
0 1 1 1
1 0 0 1
1 0 1 1
1 1 0 1
1 1 1 0


In [ ]:
#NOR GATE 
col = int(input("Enter the number of inputs"))
row = pow(2,col) 

arr = [None] * col
matrix = [[]]
generateAllBinaryStrings(col,arr,0)

print()

W = -1*(np.ones((col,) , dtype='int'))

for i in range(1,row+1):
  sum = 0
  for j in range(col):
    sum += matrix[i][j] * W[j]
  if sum >= 0:
    for r in range(col):
      print(matrix[i][r],end =' ')
    print(1)
  else:
    for r in range(col):
      print(matrix[i][r],end=' ')
    print(0)

Enter the number of inputs3

0 0 0 1
0 0 1 0
0 1 0 0
0 1 1 0
1 0 0 0
1 0 1 0
1 1 0 0
1 1 1 0


In [ ]:
#NOT 

x = [0,1]
w = -1
t = 0

for i in range(len(x)):
  if x[i]*w >= t:
    print("~",x[i],":",1)
  else:
    print("~",x[i],":",0)

~ 0 : 1
~ 1 : 0


# PERCEPTRON

**Discrete**

In [34]:
import numpy as np 
import itertools
def unipolar(result):
  return 1 if(result >=0) else 0
def bipolar(result):
  return 1 if(result >=0) else -1
def predictt(X,weights,type):
  result = np.dot(X,weights)
  if type == "unipolar":
    return unipolar(result)
  else:
    return bipolar(result)
def train(X,y,weights,type,epochs = 500,c=0.5):
  for epoch in range(epochs):
    loss = 0
    for Xi,yi in zip(X,y):
      y_pred = predictt(Xi,weights,type)
      r = yi - y_pred
      loss += abs(r)
      delta_w = c*r*Xi
      weights += delta_w
    print(f'Weights after epoch {epoch} : ',weights)
    if loss == 0:
      break
  print('Learned Weights : ',weights)
  weights = weights.reshape((n+1,1))
  test(X,y,weights,type)
def test(X,y,learned_weights,type):
  results = np.dot(X,learned_weights).flatten()
  print("Actual Values : ",y)
  if type == "unipolar":
    y_pred = np.array([1 if result >=0 else 0 for result in results ])
    print('Predicted Values : ', y_pred)
  if type == "bipolar":
    y_pred = np.array([1 if result >=0 else -1 for result in results ])
    print('Predicted Values : ', y_pred)
n = int(input("enter number of bits  "))
X = np.array([list(i) + [1] for i in itertools.product([0,1],repeat = n)])
weights = input(f'Enter {n} initial weights and 1 bias : ')
weights = np.array([float(weight) for weight in weights.split()],dtype='longdouble')

print()

#AND GATE 
print('---- AND GATE USING PERCEPTRON ----')
y = np.array([0] * (2**n))
y[-1] = 1
train(X,y,weights.copy(),'unipolar')

print('---- OR GATE USING PERCEPTRON ----')
y = np.array([1]*(2**n))
y[0] = 0
train(X, y, weights.copy(), 'unipolar')
print()
print()

# 3) NOR GATE UNIPOLAR
print('---- NOR GATE USING PERCEPTRON ----')
y = np.array([0]*(2**n))
y[0] = 1
train(X, y, weights.copy(), 'unipolar')
print()
print()

# 4) NAND GATE UNIPOLAR
print('---- NAND GATE USING PERCEPTRON ----')
y = np.array([1]*(2**n))
y[-1] = 0
train(X, y, weights.copy(), 'unipolar')
print()
print()

enter number of bits  3
Enter 3 initial weights and 1 bias : 1 1 1 0

---- AND GATE USING PERCEPTRON ----
Weights after epoch 0 :  [ 1.   1.   0.5 -1.5]
Weights after epoch 1 :  [ 1.5  1.   0.5 -1.5]
Weights after epoch 2 :  [ 1.5  0.5  0.5 -2. ]
Weights after epoch 3 :  [ 1.5  1.   0.5 -2. ]
Weights after epoch 4 :  [ 1.5  1.5  0.5 -2. ]
Weights after epoch 5 :  [ 1.5  1.   0.5 -2.5]
Weights after epoch 6 :  [ 1.5  1.   1.  -2.5]
Weights after epoch 7 :  [ 1.5  1.5  1.  -2.5]
Weights after epoch 8 :  [ 1.5  1.   0.5 -3. ]
Weights after epoch 9 :  [ 1.5  1.   0.5 -3. ]
Learned Weights :  [ 1.5  1.   0.5 -3. ]
Actual Values :  [0 0 0 0 0 0 0 1]
Predicted Values :  [0 0 0 0 0 0 0 1]
---- OR GATE USING PERCEPTRON ----
Weights after epoch 0 :  [ 1.   1.   1.  -0.5]
Weights after epoch 1 :  [ 1.   1.   1.  -0.5]
Learned Weights :  [ 1.   1.   1.  -0.5]
Actual Values :  [0 1 1 1 1 1 1 1]
Predicted Values :  [0 1 1 1 1 1 1 1]


---- NOR GATE USING PERCEPTRON ----
Weights after epoch 0 :  [ 1.

**Continuous**

In [35]:
#only activation function changes for continuous that is as follows :
def bipolar_activation(net, lambdaa = 1):
    return (2/(1+np.exp(-lambdaa*net))) - 1

def unipolar_activation(net, lambdaa = 0.3):
    return (1/(1+np.exp(-lambdaa*net)))

# Momentum based gradient descent (vanilla)

In [14]:
import numpy as np
def predict(X,weights,l=1):
  result = np.dot(X,weights)
  return (1/(1+np.exp(-l * result)))
def calculate_derivate(X,y,y_pred):
  return ((y_pred - y) * (y_pred) * (1-y_pred) * X)
def calculate_error(y,y_pred):
  return np.square(y_pred - y)
def momentum_vanilla_gradient_descent(X,y,weights,epochs=1000,learning_rate=0.01,gamma = 0.9):
  velocity = 0
  for epoch in range(epochs):
    dw =0
    error = 0
    for Xi,yi in zip(X,y):
      y_pred = predict(Xi,weights)
      dw += calculate_derivate(Xi,yi,y_pred)
      error += calculate_error(yi,y_pred)

    velocity = (gamma*velocity) + (learning_rate * dw)
    
    weights -= velocity
    
    error /= (2*len(X))

    if(epoch+1)%50 == 0:
      print(f'Weights after epoch {epoch+1} :',weights)
      print(f'Error after epoch {epoch+1} :',error)

def momentum_stochastic_gradient_descent(X,y,weights,epochs=1000,learning_rate=0.01,gamma = 0.9):
  velocity = 0
  for epoch in range(epochs):
    
    error = 0
    for Xi,yi in zip(X,y):
      y_pred = predict(Xi,weights)
      dw = calculate_derivate(Xi,yi,y_pred)
      error += calculate_error(yi,y_pred)

      velocity = (gamma*velocity) + (learning_rate * dw)
      
      weights -= velocity
      
    error /= (2*len(X))

    if(epoch+1)%50 == 0:
      print(f'Weights after epoch {epoch+1} :',weights)
      print(f'Error after epoch {epoch+1} :',error)

def momentum_minibatch_gradient_descent(X,y,weights,epochs=1000,learning_rate=0.01,gamma = 0.9,batch=2):
  velocity = 0
  for epoch in range(epochs):
    dw =0
    error = 0
    i=0
    for Xi,yi in zip(X,y):
      y_pred = predict(Xi,weights)
      dw += calculate_derivate(Xi,yi,y_pred)
      i += 1
      error += calculate_error(yi,y_pred)
      if i%batch == 0 or i==len(X):
        velocity = (gamma*velocity) + (learning_rate * dw)
        weights -= velocity
        #important  
        dw = 0
    
    error /= (2*len(X))

    if(epoch+1)%50 == 0:
      print(f'Weights after epoch {epoch+1} :',weights)
      print(f'Error after epoch {epoch+1} :',error)


X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

weights = np.array([-1,1],dtype='longdouble')

momentum_vanilla_gradient_descent(X,y,weights)

Weights after epoch 50 : [-0.90261693  0.74698767]
Error after epoch 50 : [0.13410836]
Weights after epoch 100 : [-0.73675606  0.55386541]
Error after epoch 100 : [0.13093365]
Weights after epoch 150 : [-0.56473959  0.42497552]
Error after epoch 150 : [0.1286732]
Weights after epoch 200 : [-0.41647069  0.32564855]
Error after epoch 200 : [0.12712563]
Weights after epoch 250 : [-0.30035394  0.24623578]
Error after epoch 250 : [0.12616959]
Weights after epoch 300 : [-0.21418839  0.18361179]
Error after epoch 300 : [0.1256235]
Weights after epoch 350 : [-0.15206796  0.13537449]
Error after epoch 350 : [0.12532644]
Weights after epoch 400 : [-0.10788571  0.09897339]
Error after epoch 400 : [0.12516926]
Weights after epoch 450 : [-0.07661391  0.07192456]
Error after epoch 450 : [0.12508731]
Weights after epoch 500 : [-0.05448972  0.0520454 ]
Error after epoch 500 : [0.12504492]
Weights after epoch 550 : [-0.03881439  0.03754789]
Error after epoch 550 : [0.12502308]
Weights after epoch 600 :

# Nesterov Accelerator based GD (Stochastic)

In [15]:
import numpy as np

def predict(X,weights,l=1):
  result = np.dot(X,weights)
  return (1/(1+np.exp(-l * result)))
def calculate_derivate(X,y,y_pred):
  return ((y_pred - y) * (y_pred) * (1-y_pred) * X)
def calculate_error(y,y_pred):
  return np.square(y_pred - y)

def nesterov_stochastic_gradient_descent(X,y,weights,epochs=500,learning_rate=0.01,gamma = 0.9):
  velocity = 0
  for epoch in range(epochs):
    error = 0
    for Xi,yi in zip(X,y):
      #important for nesterov
      w_lookahead = weights - (gamma * velocity)
      y_pred = predict(Xi,w_lookahead)
      dw = calculate_derivate(Xi,yi,y_pred)
      error += calculate_error(yi,y_pred)

      velocity = (gamma*velocity) + (learning_rate * dw)
      weights -= velocity 

    error /= (2*len(X))
    if (epoch+1)%50 == 0:
      print(f'Weights after epoch {epoch+1} : ',weights)
      print(f'Error after epoch {epoch+1} : ',error) 
def nesterov_vanilla_gradient_descent(X,y,weights,epochs=500,learning_rate=0.01,gamma = 0.9):
  velocity = 0
  for epoch in range(epochs):
    error = 0
    dw = 0
    #note the change  lookahead calculated here in vanilla & mini batch 
    #important for nesterov
    w_lookahead = weights - (gamma * velocity)
    for Xi,yi in zip(X,y):

      y_pred = predict(Xi,w_lookahead)
      dw += calculate_derivate(Xi,yi,y_pred)
      error += calculate_error(yi,y_pred)

    velocity = (gamma*velocity) + (learning_rate * dw)
    weights -= velocity 

    error /= (2*len(X))
    if (epoch+1)%50 == 0:
      print(f'Weights after epoch {epoch+1} : ',weights)
      print(f'Error after epoch {epoch+1} : ',error) 
def nesterov_minibatch_gradient_descent(X,y,weights,epochs=500,learning_rate=0.01,gamma = 0.9,batch=2):
  velocity = 0
  for epoch in range(epochs):
    error = 0
    dw = 0
    i = 0
    #note the change  lookahead calculated here in vanilla & mini batch 
    #important for nesterov
    w_lookahead = weights - (gamma * velocity)
    for Xi,yi in zip(X,y):

      y_pred = predict(Xi,w_lookahead)
      dw += calculate_derivate(Xi,yi,y_pred)
      i+=1
      error += calculate_error(yi,y_pred)
      
      if i%batch == 0 or i == len(X):

        velocity = (gamma*velocity) + (learning_rate * dw)
        weights -= velocity 
        dw = 0
        w_lookahead = weights - (gamma * velocity)

    error /= (2*len(X))
    if (epoch+1)%50 == 0:
      print(f'Weights after epoch {epoch+1} : ',weights)
      print(f'Error after epoch {epoch+1} : ',error) 
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

weights = np.array([-1,1],dtype='longdouble')

nesterov_stochastic_gradient_descent(X,y,weights)

Weights after epoch 50 :  [-0.87678323  0.72832187]
Error after epoch 50 :  [0.13373068]
Weights after epoch 100 :  [-0.71091533  0.54772924]
Error after epoch 100 :  [0.13073888]
Weights after epoch 150 :  [-0.54789621  0.42053231]
Error after epoch 150 :  [0.12861488]
Weights after epoch 200 :  [-0.4089435   0.32267278]
Error after epoch 200 :  [0.12717828]
Weights after epoch 250 :  [-0.29961063  0.24550554]
Error after epoch 250 :  [0.12628666]
Weights after epoch 300 :  [-0.21746087  0.18500945]
Error after epoch 300 :  [0.12576834]
Weights after epoch 350 :  [-0.15726532  0.13824996]
Error after epoch 350 :  [0.12547925]
Weights after epoch 400 :  [-0.11369221  0.10260813]
Error after epoch 400 :  [0.1253219]
Weights after epoch 450 :  [-0.08230163  0.07574954]
Error after epoch 450 :  [0.12523746]
Weights after epoch 500 :  [-0.05970587  0.05568712]
Error after epoch 500 :  [0.12519253]


# Adagrad Mini batch  

In [17]:
def adagrad_minibatch_gd(X,y,weights,epochs=500,learning_rate=0.01,epsilon=1e08,batch=2):
  velocity = 0
  for epoch in range(epochs):
    error = 0
    dw = 0
    i = 0
    for Xi,yi in zip(X,y):
      y_pred = predict(Xi,weights)
      dw += calculate_derivate(Xi,yi,y_pred)
      i+= 1
      error += calculate_error(yi,y_pred)

      if i%batch == 0 or i == len(X):
        #note the dofference in vdelocity updation 
        velocity = velocity + (dw ** 2)
        #note change in weight update rule
        weights -= ((learning_rate*dw) / (np.sqrt(velocity + epsilon)))
        dw = 0
    error /= (2 * len(X))
    if (epoch+1)%50 == 0:
      print(f'Weights after epoch {epoch+1} : ',weights)
      print(f'Error after epoch {epoch+1} : ',error)

def adagrad_vanilla_gd(X,y,weights,epochs=500,learning_rate=0.01,epsilon=1e08,batch=2):
  velocity = 0
  for epoch in range(epochs):
    error = 0
    dw = 0

    for Xi,yi in zip(X,y):
      y_pred = predict(Xi,weights)
      dw += calculate_derivate(Xi,yi,y_pred)
      
      error += calculate_error(yi,y_pred)

      
    #note the dofference in vdelocity updation 
    velocity = velocity + (dw ** 2)
    #note change in weight update rule
    weights -= ((learning_rate*dw) / (np.sqrt(velocity + epsilon)))
    
    error /= (2 * len(X))
    if (epoch+1)%50 == 0:
      print(f'Weights after epoch {epoch+1} : ',weights)
      print(f'Error after epoch {epoch+1} : ',error)
def adagrad_stochastic_gd(X,y,weights,epochs=500,learning_rate=0.01,epsilon=1e08,batch=2):
  velocity = 0
  for epoch in range(epochs):
    error = 0
   
    for Xi,yi in zip(X,y):
      y_pred = predict(Xi,weights)
      dw = calculate_derivate(Xi,yi,y_pred)
      
      error += calculate_error(yi,y_pred)

      
      #note the dofference in vdelocity updation 
      velocity = velocity + (dw ** 2)
      #note change in weight update rule
      weights -= ((learning_rate*dw) / (np.sqrt(velocity + epsilon)))
    
    error /= (2 * len(X))
    if (epoch+1)%50 == 0:
      print(f'Weights after epoch {epoch+1} : ',weights)
      print(f'Error after epoch {epoch+1} : ',error)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

weights = np.array([-1,1],dtype='longdouble')

adagrad_minibatch_gd(X,y,weights)

Weights after epoch 50 :  [-0.99999906  0.99999639]
Error after epoch 50 :  [0.13834695]
Weights after epoch 100 :  [-0.99999813  0.99999279]
Error after epoch 100 :  [0.13834688]
Weights after epoch 150 :  [-0.99999719  0.99998918]
Error after epoch 150 :  [0.13834681]
Weights after epoch 200 :  [-0.99999625  0.99998558]
Error after epoch 200 :  [0.13834674]
Weights after epoch 250 :  [-0.99999532  0.99998197]
Error after epoch 250 :  [0.13834667]
Weights after epoch 300 :  [-0.99999438  0.99997836]
Error after epoch 300 :  [0.1383466]
Weights after epoch 350 :  [-0.99999344  0.99997476]
Error after epoch 350 :  [0.13834653]
Weights after epoch 400 :  [-0.99999251  0.99997115]
Error after epoch 400 :  [0.13834646]
Weights after epoch 450 :  [-0.99999157  0.99996755]
Error after epoch 450 :  [0.1383464]
Weights after epoch 500 :  [-0.99999063  0.99996394]
Error after epoch 500 :  [0.13834633]


# Adam GD 

In [19]:
def predict(Xi,weights,l=1):
  result = np.dot(Xi,weights)
  return (1/(1+np.exp(-l * result)))
def calculate_derivate(Xi,yi,y_pred):
  return((y_pred-yi) * y_pred * (1-y_pred) * Xi)
def calculate_error(yi,y_pred):
  return np.square(y_pred - yi)

def adam_vanilla_gd(X,y,weights,epochs=500,learning=0.01,epsilon=1e-8,beta1=0.9,beta2=0.999,batch=2):
  #new
  momentum = 0
  velocity =0
  for epoch in range(epochs):
    dw = 0
    error = 0
    for Xi,yi in zip(X,y):
      y_pred = predict(Xi,weights)
      dw += calculate_derivate(Xi,yi,y_pred)
      error += calculate_error(yi,y_pred)
    
    #note the additions - momentum and  velocity 
    momentum = (beta1 * momentum) + ((1-beta1) * dw)
    velocity = (beta2 * velocity) + ((1-beta2) * (dw**2))
    step = epoch +1
    momentum_cap = momentum / (1 - (beta1 ** step))
    velocity_cap = velocity / (1- (beta2 ** step))
    weights -= ((learning*momentum_cap) / (np.sqrt(velocity_cap + epsilon)))

    error /= (2*len(X))

    if (epoch+1)%50 == 0:
      print(f'Weights after epoch {epoch+1}',weights)
      print(f'Error after epoch {epoch +1}',error)

def adam_stochastic_gd(X,y,weights,epochs=500,learning=0.01,epsilon=1e-8,beta1=0.9,beta2=0.999,batch=2):
  #new
  momentum = 0
  velocity =0
  #note in stochastic 
  step = 0
  for epoch in range(epochs):
   
    error = 0
    for Xi,yi in zip(X,y):
      y_pred = predict(Xi,weights)
      dw = calculate_derivate(Xi,yi,y_pred)
      error += calculate_error(yi,y_pred)
    
      #note the additions - momentum and  velocity 
      momentum = (beta1 * momentum) + ((1-beta1) * dw)
      velocity = (beta2 * velocity) + ((1-beta2) * (dw**2))

      #change of step updation in stiochastic 
      step += 1

      momentum_cap = momentum / (1 - (beta1 ** step))
      velocity_cap = velocity / (1- (beta2 ** step))
      weights -= ((learning*momentum_cap) / (np.sqrt(velocity_cap + epsilon)))

    error /= (2*len(X))

    if (epoch+1)%50 == 0:
      print(f'Weights after epoch {epoch+1}',weights)
      print(f'Error after epoch {epoch +1}',error)

def adam_minibatch_gd(X,y,weights,epochs=500,learning=0.01,epsilon=1e-8,beta1=0.9,beta2=0.999,batch=2):
  #new
  momentum = 0
  velocity =0

  #see step initialisation
  step = 0
  for epoch in range(epochs):
    dw = 0
    i=0
    error = 0
    for Xi,yi in zip(X,y):
      y_pred = predict(Xi,weights)
      dw += calculate_derivate(Xi,yi,y_pred)
      i+=1
      error += calculate_error(yi,y_pred)
      if i%batch == 0 or i == len(X):
        #note the additions - momentum and  velocity 
        momentum = (beta1 * momentum) + ((1-beta1) * dw)
        velocity = (beta2 * velocity) + ((1-beta2) * (dw**2))

        #note change in step updation 
        step +=1
        momentum_cap = momentum / (1 - (beta1 ** step))
        velocity_cap = velocity / (1- (beta2 ** step))
        weights -= ((learning*momentum_cap) / (np.sqrt(velocity_cap + epsilon)))
        #important 
        dw = 0
        
    error /= (2*len(X))

    if (epoch+1)%50 == 0:
      print(f'Weights after epoch {epoch+1}',weights)
      print(f'Error after epoch {epoch +1}',error)
def adam_vanilla_gd(X,y,weights,epochs=500,learning=0.01,epsilon=1e-8,beta1=0.9,beta2=0.999,batch=2):
  #new
  momentum = 0
  velocity =0
  for epoch in range(epochs):
    dw = 0
    error = 0
    for Xi,yi in zip(X,y):
      y_pred = predict(Xi,weights)
      dw += calculate_derivate(Xi,yi,y_pred)
      error += calculate_error(yi,y_pred)
    
    #note the additions - momentum and  velocity 
    momentum = (beta1 * momentum) + ((1-beta1) * dw)
    velocity = (beta2 * velocity) + ((1-beta2) * (dw**2))
    step = epoch +1
    momentum_cap = momentum / (1 - (beta1 ** step))
    velocity_cap = velocity / (1- (beta2 ** step))
    weights -= ((learning*momentum_cap) / (np.sqrt(velocity_cap + epsilon)))

    error /= (2*len(X))

    if (epoch+1)%50 == 0:
      print(f'Weights after epoch {epoch+1}',weights)
      print(f'Error after epoch {epoch +1}',error)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0],[1],[1],[0]])

weights = np.array([-1,1],dtype="longdouble")
adam_vanilla_gd(X,y,weights)


Weights after epoch 50 [-0.4926079   0.53320742]
Error after epoch 50 [0.12916512]
Weights after epoch 100 [-0.14472774  0.2050715 ]
Error after epoch 100 [0.12555797]
Weights after epoch 150 [-0.03469891  0.05103675]
Error after epoch 150 [0.12503417]
Weights after epoch 200 [-0.00547008  0.00820874]
Error after epoch 200 [0.12500089]
Weights after epoch 250 [-0.00046226  0.0006961 ]
Error after epoch 250 [0.12500001]
Weights after epoch 300 [-2.06306744e-06  3.22643532e-06]
Error after epoch 300 [0.125]
Weights after epoch 350 [ 2.21052128e-06 -3.31254379e-06]
Error after epoch 350 [0.125]
Weights after epoch 400 [-2.41936542e-08  3.66464901e-08]
Error after epoch 400 [0.125]
Weights after epoch 450 [-9.20831215e-09  1.38565973e-08]
Error after epoch 450 [0.125]
Weights after epoch 500 [ 7.34862879e-10 -1.09914563e-09]
Error after epoch 500 [0.125]


# RMS Prop

In [18]:
def rms_vanilla_gd(X,y,weights,epochs=500,learning_rate=0.01,epsilon=1e-8,beta=0.5,batch=2):
  velocity = 0
  for epoch in range(epochs):
    error = 0
    dw = 0
    for Xi,yi in zip(X,y):
      y_pred = predict(Xi,weights)
      dw += calculate_derivate(Xi,yi,y_pred)
      error += calculate_error(yi,y_pred)
    
    #note this change in velocity update 
    velocity = (beta * velocity) + ((1-beta) * (dw**2))
    #note this weight update similar to adagrad  
    weights -= ((learning_rate * dw) / (np.sqrt(velocity + epsilon)))
    error /= (2*len(X))
    if (epoch+1)%50 == 0:
      print(f'Weights after epoch {epoch+1} : ',weights)
      print(f'Error after epoch {epoch+1} : ',error)
def rms_stochastic_gd(X,y,weights,epochs=500,learning_rate=0.01,epsilon=1e-8,beta=0.5,batch=2):
  velocity = 0
  for epoch in range(epochs):
    error = 0
    
    for Xi,yi in zip(X,y):
      y_pred = predict(Xi,weights)
      dw = calculate_derivate(Xi,yi,y_pred)
      error += calculate_error(yi,y_pred)
    
    #note this change in velocity update 
      velocity = (beta * velocity) + ((1-beta) * (dw**2))
      #note this weight update similar to adagrad  
      weights -= ((learning_rate * dw) / (np.sqrt(velocity + epsilon)))
    error /= (2*len(X))
    if (epoch+1)%50 == 0:
      print(f'Weights after epoch {epoch+1} : ',weights)
      print(f'Error after epoch {epoch+1} : ',error)
def rms_minibatch_gd(X,y,weights,epochs=500,learning_rate=0.01,epsilon=1e-8,beta=0.5,batch=2):
  velocity = 0
  for epoch in range(epochs):
    error = 0
    dw = 0
    i=0
    for Xi,yi in zip(X,y):
      y_pred = predict(Xi,weights)
      dw += calculate_derivate(Xi,yi,y_pred)
      i+=1
      error += calculate_error(yi,y_pred)
      if i%batch == 0 or i==len(X):


        #note this change in velocity update 
        velocity = (beta * velocity) + ((1-beta) * (dw**2))
        #note this weight update similar to adagrad  
        weights -= ((learning_rate * dw) / (np.sqrt(velocity + epsilon)))
        dw = 0
        
    error /= (2*len(X))
    if (epoch+1)%50 == 0:
      print(f'Weights after epoch {epoch+1} : ',weights)
      print(f'Error after epoch {epoch+1} : ',error)

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

weights = np.array([-1,1],dtype='longdouble')

rms_vanilla_gd(X,y,weights)



Weights after epoch 50 :  [-0.49195468  0.49939579]
Error after epoch 50 :  [0.12884365]
Weights after epoch 100 :  [-0.02077174  0.02681676]
Error after epoch 100 :  [0.12501587]
Weights after epoch 150 :  [-0.00495911 -0.00495911]
Error after epoch 150 :  [0.12500116]
Weights after epoch 200 :  [-0.00495911 -0.00495911]
Error after epoch 200 :  [0.12500116]
Weights after epoch 250 :  [-0.00495911 -0.00495911]
Error after epoch 250 :  [0.12500116]
Weights after epoch 300 :  [-0.00495911 -0.00495911]
Error after epoch 300 :  [0.12500116]
Weights after epoch 350 :  [-0.00495911 -0.00495911]
Error after epoch 350 :  [0.12500116]
Weights after epoch 400 :  [-0.00495911 -0.00495911]
Error after epoch 400 :  [0.12500116]
Weights after epoch 450 :  [-0.00495911 -0.00495911]
Error after epoch 450 :  [0.12500116]
Weights after epoch 500 :  [-0.00495911 -0.00495911]
Error after epoch 500 :  [0.12500116]


# Calculate Max Pooling 

In [29]:

def pool(matrix,stride,pool_size):
  paddedMatrix = np.array([[0]*paddedMatrix_width for i in range(paddedMatrix_height)])
  height = len(matrix)
  width = len(matrix[0])
  i = 0
  j = 0
  oi = 0
  oj = 0

  while(i + pool_size <= height):
    while(j + pool_size <= width):
      pool_window =[] 

      for h in range(pool_size):
        for w in range(pool_size):
          pool_window.append(matrix[i+h][j+w])
      
      paddedMatrix[oi][oj] = max(pool_window)
      oj += 1
      j = j+stride 
    i  = i+stride
    oi += 1
    j=0
    oj = 0
  return paddedMatrix
print("Creating Original Matrix ")

og_height = int(input("Enter the height of matrix"))
og_width = int(input("Enter the width of matrix"))
matrix = [[0]*og_width for i in range(og_height)]

for i in range(og_height):
  for j in range(og_width):
    matrix[i][j] = int(input(f'Enter the values of matrix[{i}][{j}] :'))

pad_amt = int(input("enter the amount of padding"))
pad_val = int(input("Enter the padding value"))
stride = int(input("enter the amount of stride"))
pool_size = int(input("enter the pool size "))

paddedMatrix_width = ((og_width + (2*pad_amt) - pool_size)//stride) + 1
paddedMatrix_height = ((og_height + (2*pad_amt) - pool_size)//stride) + 1

matrix = np.array(matrix)
print()

print("Input Matrix : ")
print(matrix)
print()

matrix = np.pad(matrix,pad_amt,constant_values=pad_val)
print("After Padding : ")
print(matrix)
print()
83
matrix = pool(matrix,stride,pool_size)
print('After Pooling :- ')
print(matrix)

Creating Original Matrix 
Enter the height of matrix3
Enter the width of matrix3
Enter the values of matrix[0][0] :2
Enter the values of matrix[0][1] :3
Enter the values of matrix[0][2] :4
Enter the values of matrix[1][0] :5
Enter the values of matrix[1][1] :6
Enter the values of matrix[1][2] :7
Enter the values of matrix[2][0] :8
Enter the values of matrix[2][1] :9
Enter the values of matrix[2][2] :2
enter the amount of padding2
Enter the padding value0
enter the amount of stride2
enter the pool size 2

Input Matrix : 
[[2 3 4]
 [5 6 7]
 [8 9 2]]

After Padding : 
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 2 3 4 0 0]
 [0 0 5 6 7 0 0]
 [0 0 8 9 2 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]

After P5ooling :- 
[[0 0 0]
 [0 6 7]
 [0 9 2]]


# Calculate Convolution

In [31]:
def convolve(matrix,filter,stride):
  op_matrix = np.array([[0]*filteredMatrix_width for i in range(filteredMatrix_height)])

  height = len(matrix)
  width = len(matrix[0])

  i=0
  j=0
  oi = 0
  oj = 0

  while(i+filter_height <= height):
    while(j+filter_width <= width):
      window = []
      for h in range(filter_height):
        for w in range(filter_width):
          window.append(matrix[i+h][j+w])
      
      op_matrix[oi][oj] = np.dot(np.array(window),filter.ravel())
      oj += 1
      j = j+stride
    i = i+stride
    oi += 1
    j= 0
    oj =0
  return op_matrix

og_height = int(input("Enter the height of matrix"))
og_width = int(input("Enter the width of matrix"))
matrix = [[0]*og_width for i in range(og_height)]

for i in range(og_height):
  for j in range(og_width):
    matrix[i][j] = int(input(f'Enter the values of matrix[{i}][{j}] :'))


filter_height = int(input("Filter Height"))
filter_width = int(input("Filter Width"))

filter = [[0]* filter_width for i in range(filter_height)]

for i in range(filter_height):
  for j in range(filter_width):
    filter[i][j] = int(input(f'Enter value of filter[{i}][{j}] : '))

pad_amt = int(input("enter the amount of padding"))
pad_val = int(input("Enter the padding value"))
stride = int(input("enter the amount of stride"))


filteredMatrix_width = ((og_width + (2*pad_amt) - filter_width)//stride) + 1
filteredMatrix_height = ((og_height + (2*pad_amt) - filter_height)//stride) + 1

filter = np.array(filter)
matrix = np.array(matrix)

print("Input matrix") 
print(matrix)
print()
print("Filter : ")
print(filter)
print()
matrix = np.pad(matrix,pad_amt,constant_values=pad_val)
print("After Padding : ")
print(matrix)
print()
filteredOp = convolve(matrix,filter,stride)
print("After Filter ")
print(filteredOp)



Enter the height of matrix3
Enter the width of matrix3
Enter the values of matrix[0][0] :2
Enter the values of matrix[0][1] :3
Enter the values of matrix[0][2] :4
Enter the values of matrix[1][0] :5
Enter the values of matrix[1][1] :6
Enter the values of matrix[1][2] :7
Enter the values of matrix[2][0] :8
Enter the values of matrix[2][1] :9
Enter the values of matrix[2][2] :2
Filter Height2
Filter Width2
Enter value of filter[0][0] : 2
Enter value of filter[0][1] : 2
Enter value of filter[1][0] : 2
Enter value of filter[1][1] : 2
enter the amount of padding2
Enter the padding value0
enter the amount of stride2
Input matrix
[[2 3 4]
 [5 6 7]
 [8 9 2]]

Filter : 
[[2 2]
 [2 2]]

After Padding : 
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 2 3 4 0 0]
 [0 0 5 6 7 0 0]
 [0 0 8 9 2 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
After Filter 
[[ 0  0  0]
 [ 0 32 22]
 [ 0 34  4]]
